[[constraint]]
  branch = "master"
  name = "github.com/grafana/grafana_plugin_model"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "signalflow"
  name = "github.com/signalfx/signalfx-go"

[[constraint]]
  branch = "master"
  name = "github.com/davecgh/go-spew"